import Link from 'next/link';
import './globals.css';
import { LoginBtn, LogoutBtn } from '@/components/SignBtn';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/pages/api/auth/[...nextauth]';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const session = await getServerSession(authOptions);

    return (
        <html lang='en'>
            <body>
                <div className='navbar'>
                    <Link href='/' className='logo'>
                        Appleforum
                    </Link>
                    <Link href='/list'>List</Link>
                    <Link href='/write'>Write</Link>
                    {session ? <LogoutBtn /> : <LoginBtn />}
                </div>
                {children}
            </body>
        </html>
    );
}
